apiVersion: v1
kind: Service
metadata:
  name: todo-list-app-service
spec:
  type: NodePort
  selector:
    app: todo-list
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80
