apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-hd-deployment
  labels:
    app: node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node-app-http-docker
        image: ghcr.io/ydeyeq/node-app-http-docker:main
        ports:
        - containerPort: 80
        
---

# NodePort service that chooses a random port
# on the node.
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: NodePort
  selector:
    app: node
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 80

---

#GatewayClass manifest
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  labels:
    app: node
  name: node-app-gatewayclass
spec:
  controllerName: gateway.nginx.org/nginx-gateway-controller
---

#Gateway manifest
apiVersion: gateway.nginx.org/v1alpha1
kind: NginxGateway
metadata:
  labels:
    app: node
  name: node-app-nginx-gateway
  namespace: default
spec:
  gatewayClassName: node-app-gatewayclass
  listeners:
  - name: http
    protocol: HTTP
    port: 80

---

#HTTProute manifest
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: node-app-httproute
spec:
  parentRefs:
  - name: node-app-nginx-gateway
  rules:
  - backendRefs:
    - name: node-service
