apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-app-deployment
  labels:
    app: todo-list
    dev: devops-lead-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-list
  template:
    metadata:
      labels:
        app: todo-list
    spec:
      containers:
      - name: todo-list
        image: ghcr.io/ydeyeq/getting-started-todo-app:main
        ports:
        - containerPort: 80
